// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controller/http/v1/handler/category/delete.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDeleteCategoryUsecase is a mock of DeleteCategoryUsecase interface.
type MockDeleteCategoryUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteCategoryUsecaseMockRecorder
}

// MockDeleteCategoryUsecaseMockRecorder is the mock recorder for MockDeleteCategoryUsecase.
type MockDeleteCategoryUsecaseMockRecorder struct {
	mock *MockDeleteCategoryUsecase
}

// NewMockDeleteCategoryUsecase creates a new mock instance.
func NewMockDeleteCategoryUsecase(ctrl *gomock.Controller) *MockDeleteCategoryUsecase {
	mock := &MockDeleteCategoryUsecase{ctrl: ctrl}
	mock.recorder = &MockDeleteCategoryUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteCategoryUsecase) EXPECT() *MockDeleteCategoryUsecaseMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDeleteCategoryUsecase) Delete(ctx context.Context, ID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeleteCategoryUsecaseMockRecorder) Delete(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeleteCategoryUsecase)(nil).Delete), ctx, ID)
}
